# Collect Data From SQLite Databases

## What is SQLite

A file with the .sqlite extension is a lightweight SQL database file created with the SQLite software. It is a database in a file itself and implements a self-contained, full-featured, highly-reliable SQL database engine. 

We use SQLite to demonstrate the approach to access SQL databases. They follow similar steps. You just need to setup your account credentials in the `connect` so you can connect the server.

## Read an SQLite Database in Python

We use a Python package, sqlite3, to deal with SQLite databases. Once the sqlite3 package is imported, the general steps are:
1.  Create a connection object that connects the SQLite database.
2.  Create a cursor object
3.  Create a query statement
4.  Execute the query statement
5.  Fetch the query result to result
6.  If all work is done, close the connection.

We use the built-in SQLite database Chinook as the example here. We connect with the database, and show all the tables it contains.

In [1]:
import sqlite3

connection = sqlite3.connect('/content/ds_salaries.sqlite')
cursor = connection.cursor()

query = '''
SELECT name FROM sqlite_master  
WHERE type='table';
'''

cursor.execute(query)
results = cursor.fetchall()
results

[('ds_salaries',)]

## Play with the SQLite Databases

Using SQL statements, you can play with the SQLite Databases and get the data you need.

In [2]:
query = '''SELECT * 
FROM ds_salaries'''

cursor.execute(query)
results = cursor.fetchall()
results

[(None,
  'work_year',
  'experience_level',
  'employment_type',
  'job_title',
  'salary',
  'salary_currency',
  'salary_in_usd',
  'employee_residence',
  'remote_ratio',
  'company_location',
  'company_size'),
 (0,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '70000',
  'EUR',
  '79833',
  'DE',
  '0',
  'DE',
  'L'),
 (1,
  '2020',
  'SE',
  'FT',
  'Machine Learning Scientist',
  '260000',
  'USD',
  '260000',
  'JP',
  '0',
  'JP',
  'S'),
 (2,
  '2020',
  'SE',
  'FT',
  'Big Data Engineer',
  '85000',
  'GBP',
  '109024',
  'GB',
  '50',
  'GB',
  'M'),
 (3,
  '2020',
  'MI',
  'FT',
  'Product Data Analyst',
  '20000',
  'USD',
  '20000',
  'HN',
  '0',
  'HN',
  'S'),
 (4,
  '2020',
  'SE',
  'FT',
  'Machine Learning Engineer',
  '150000',
  'USD',
  '150000',
  'US',
  '50',
  'US',
  'L'),
 (5,
  '2020',
  'EN',
  'FT',
  'Data Analyst',
  '72000',
  'USD',
  '72000',
  'US',
  '100',
  'US',
  'L'),
 (6,
  '2020',
  'SE',
  'FT',
  'Lead Data Scientist',
  '190000',
  'USD',
  '190000',
  'US',
  '100',
  'US',
  'S'),
 (7,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '11000000',
  'HUF',
  '35735',
  'HU',
  '50',
  'HU',
  'L'),
 (8,
  '2020',
  'MI',
  'FT',
  'Business Data Analyst',
  '135000',
  'USD',
  '135000',
  'US',
  '100',
  'US',
  'L'),
 (9,
  '2020',
  'SE',
  'FT',
  'Lead Data Engineer',
  '125000',
  'USD',
  '125000',
  'NZ',
  '50',
  'NZ',
  'S'),
 (10,
  '2020',
  'EN',
  'FT',
  'Data Scientist',
  '45000',
  'EUR',
  '51321',
  'FR',
  '0',
  'FR',
  'S'),
 (11,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '3000000',
  'INR',
  '40481',
  'IN',
  '0',
  'IN',
  'L'),
 (12,
  '2020',
  'EN',
  'FT',
  'Data Scientist',
  '35000',
  'EUR',
  '39916',
  'FR',
  '0',
  'FR',
  'M'),
 (13,
  '2020',
  'MI',
  'FT',
  'Lead Data Analyst',
  '87000',
  'USD',
  '87000',
  'US',
  '100',
  'US',
  'L'),
 (14,
  '2020',
  'MI',
  'FT',
  'Data Analyst',
  '85000',
  'USD',
  '85000',
  'US',
  '100',
  'US',
  'L'),
 (15,
  '2020',
  'MI',
  'FT',
  'Data Analyst',
  '8000',
  'USD',
  '8000',
  'PK',
  '50',
  'PK',
  'L'),
 (16,
  '2020',
  'EN',
  'FT',
  'Data Engineer',
  '4450000',
  'JPY',
  '41689',
  'JP',
  '100',
  'JP',
  'S'),
 (17,
  '2020',
  'SE',
  'FT',
  'Big Data Engineer',
  '100000',
  'EUR',
  '114047',
  'PL',
  '100',
  'GB',
  'S'),
 (18,
  '2020',
  'EN',
  'FT',
  'Data Science Consultant',
  '423000',
  'INR',
  '5707',
  'IN',
  '50',
  'IN',
  'M'),
 (19,
  '2020',
  'MI',
  'FT',
  'Lead Data Engineer',
  '56000',
  'USD',
  '56000',
  'PT',
  '100',
  'US',
  'M'),
 (20,
  '2020',
  'MI',
  'FT',
  'Machine Learning Engineer',
  '299000',
  'CNY',
  '43331',
  'CN',
  '0',
  'CN',
  'M'),
 (21,
  '2020',
  'MI',
  'FT',
  'Product Data Analyst',
  '450000',
  'INR',
  '6072',
  'IN',
  '100',
  'IN',
  'L'),
 (22,
  '2020',
  'SE',
  'FT',
  'Data Engineer',
  '42000',
  'EUR',
  '47899',
  'GR',
  '50',
  'GR',
  'L'),
 (23,
  '2020',
  'MI',
  'FT',
  'BI Data Analyst',
  '98000',
  'USD',
  '98000',
  'US',
  '0',
  'US',
  'M'),
 (24,
  '2020',
  'MI',
  'FT',
  'Lead Data Scientist',
  '115000',
  'USD',
  '115000',
  'AE',
  '0',
  'AE',
  'L'),
 (25,
  '2020',
  'EX',
  'FT',
  'Director of Data Science',
  '325000',
  'USD',
  '325000',
  'US',
  '100',
  'US',
  'L'),
 (26,
  '2020',
  'EN',
  'FT',
  'Research Scientist',
  '42000',
  'USD',
  '42000',
  'NL',
  '50',
  'NL',
  'L'),
 (27,
  '2020',
  'SE',
  'FT',
  'Data Engineer',
  '720000',
  'MXN',
  '33511',
  'MX',
  '0',
  'MX',
  'S'),
 (28,
  '2020',
  'EN',
  'CT',
  'Business Data Analyst',
  '100000',
  'USD',
  '100000',
  'US',
  '100',
  'US',
  'L'),
 (29,
  '2020',
  'SE',
  'FT',
  'Machine Learning Manager',
  '157000',
  'CAD',
  '117104',
  'CA',
  '50',
  'CA',
  'L'),
 (30,
  '2020',
  'MI',
  'FT',
  'Data Engineering Manager',
  '51999',
  'EUR',
  '59303',
  'DE',
  '100',
  'DE',
  'S'),
 (31,
  '2020',
  'EN',
  'FT',
  'Big Data Engineer',
  '70000',
  'USD',
  '70000',
  'US',
  '100',
  'US',
  'L'),
 (32,
  '2020',
  'SE',
  'FT',
  'Data Scientist',
  '60000',
  'EUR',
  '68428',
  'GR',
  '100',
  'US',
  'L'),
 (33,
  '2020',
  'MI',
  'FT',
  'Research Scientist',
  '450000',
  'USD',
  '450000',
  'US',
  '0',
  'US',
  'M'),
 (34,
  '2020',
  'MI',
  'FT',
  'Data Analyst',
  '41000',
  'EUR',
  '46759',
  'FR',
  '50',
  'FR',
  'L'),
 (35,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '65000',
  'EUR',
  '74130',
  'AT',
  '50',
  'AT',
  'L'),
 (36,
  '2020',
  'MI',
  'FT',
  'Data Science Consultant',
  '103000',
  'USD',
  '103000',
  'US',
  '100',
  'US',
  'L'),
 (37,
  '2020',
  'EN',
  'FT',
  'Machine Learning Engineer',
  '250000',
  'USD',
  '250000',
  'US',
  '50',
  'US',
  'L'),
 (38,
  '2020',
  'EN',
  'FT',
  'Data Analyst',
  '10000',
  'USD',
  '10000',
  'NG',
  '100',
  'NG',
  'S'),
 (39,
  '2020',
  'EN',
  'FT',
  'Machine Learning Engineer',
  '138000',
  'USD',
  '138000',
  'US',
  '100',
  'US',
  'S'),
 (40,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '45760',
  'USD',
  '45760',
  'PH',
  '100',
  'US',
  'S'),
 (41,
  '2020',
  'EX',
  'FT',
  'Data Engineering Manager',
  '70000',
  'EUR',
  '79833',
  'ES',
  '50',
  'ES',
  'L'),
 (42,
  '2020',
  'MI',
  'FT',
  'Machine Learning Infrastructure Engineer',
  '44000',
  'EUR',
  '50180',
  'PT',
  '0',
  'PT',
  'M'),
 (43,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '106000',
  'USD',
  '106000',
  'US',
  '100',
  'US',
  'L'),
 (44,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '88000',
  'GBP',
  '112872',
  'GB',
  '50',
  'GB',
  'L'),
 (45,
  '2020',
  'EN',
  'PT',
  'ML Engineer',
  '14000',
  'EUR',
  '15966',
  'DE',
  '100',
  'DE',
  'S'),
 (46,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '60000',
  'GBP',
  '76958',
  'GB',
  '100',
  'GB',
  'S'),
 (47,
  '2020',
  'SE',
  'FT',
  'Data Engineer',
  '188000',
  'USD',
  '188000',
  'US',
  '100',
  'US',
  'L'),
 (48,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '105000',
  'USD',
  '105000',
  'US',
  '100',
  'US',
  'L'),
 (49,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '61500',
  'EUR',
  '70139',
  'FR',
  '50',
  'FR',
  'L'),
 (50,
  '2020',
  'EN',
  'FT',
  'Data Analyst',
  '450000',
  'INR',
  '6072',
  'IN',
  '0',
  'IN',
  'S'),
 (51,
  '2020',
  'EN',
  'FT',
  'Data Analyst',
  '91000',
  'USD',
  '91000',
  'US',
  '100',
  'US',
  'L'),
 (52,
  '2020',
  'EN',
  'FT',
  'AI Scientist',
  '300000',
  'DKK',
  '45896',
  'DK',
  '50',
  'DK',
  'S'),
 (53,
  '2020',
  'EN',
  'FT',
  'Data Engineer',
  '48000',
  'EUR',
  '54742',
  'PK',
  '100',
  'DE',
  'L'),
 (54,
  '2020',
  'SE',
  'FL',
  'Computer Vision Engineer',
  '60000',
  'USD',
  '60000',
  'RU',
  '100',
  'US',
  'S'),
 (55,
  '2020',
  'SE',
  'FT',
  'Principal Data Scientist',
  '130000',
  'EUR',
  '148261',
  'DE',
  '100',
  'DE',
  'M'),
 (56,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '34000',
  'EUR',
  '38776',
  'ES',
  '100',
  'ES',
  'M'),
 (57,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '118000',
  'USD',
  '118000',
  'US',
  '100',
  'US',
  'M'),
 (58,
  '2020',
  'SE',
  'FT',
  'Data Scientist',
  '120000',
  'USD',
  '120000',
  'US',
  '50',
  'US',
  'L'),
 (59,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '138350',
  'USD',
  '138350',
  'US',
  '100',
  'US',
  'M'),
 (60,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '110000',
  'USD',
  '110000',
  'US',
  '100',
  'US',
  'L'),
 (61,
  '2020',
  'MI',
  'FT',
  'Data Engineer',
  '130800',
  'USD',
  '130800',
  'ES',
  '100',
  'US',
  'M'),
 (62,
  '2020',
  'EN',
  'PT',
  'Data Scientist',
  '19000',
  'EUR',
  '21669',
  'IT',
  '50',
  'IT',
  'S'),
 (63,
  '2020',
  'SE',
  'FT',
  'Data Scientist',
  '412000',
  'USD',
  '412000',
  'US',
  '100',
  'US',
  'L'),
 (64,
  '2020',
  'SE',
  'FT',
  'Machine Learning Engineer',
  '40000',
  'EUR',
  '45618',
  'HR',
  '100',
  'HR',
  'S'),
 (65,
  '2020',
  'EN',
  'FT',
  'Data Scientist',
  '55000',
  'EUR',
  '62726',
  'DE',
  '50',
  'DE',
  'S'),
 (66,
  '2020',
  'EN',
  'FT',
  'Data Scientist',
  '43200',
  'EUR',
  '49268',
  'DE',
  '0',
  'DE',
  'S'),
 (67,
  '2020',
  'SE',
  'FT',
  'Data Science Manager',
  '190200',
  'USD',
  '190200',
  'US',
  '100',
  'US',
  'M'),
 (68,
  '2020',
  'EN',
  'FT',
  'Data Scientist',
  '105000',
  'USD',
  '105000',
  'US',
  '100',
  'US',
  'S'),
 (69,
  '2020',
  'SE',
  'FT',
  'Data Scientist',
  '80000',
  'EUR',
  '91237',
  'AT',
  '0',
  'AT',
  'S'),
 (70,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '55000',
  'EUR',
  '62726',
  'FR',
  '50',
  'LU',
  'S'),
 (71,
  '2020',
  'MI',
  'FT',
  'Data Scientist',
  '37000',
  'EUR',
  '42197',
  'FR',
  '50',
  'FR',
  'S'),
 (72,
  '2021',
  'EN',
  'FT',
  'Research Scientist',
  '60000',
  'GBP',
  '82528',
  'GB',
  '50',
  'GB',
  'L'),
 (73,
  '2021',
  'EX',
  'FT',
  'BI Data Analyst',
  '150000',
  'USD',
  '150000',
  'IN',
  '100',
  'US',
  'L'),
 (74,
  '2021',
  'EX',
  'FT',
  'Head of Data',
  '235000',
  'USD',
  '235000',
  'US',
  '100',
  'US',
  'L'),
 (75,
  '2021',
  'SE',
  'FT',
  'Data Scientist',
  '45000',
  'EUR',
  '53192',
  'FR',
  '50',
  'FR',
  'L'),
 (76,
  '2021',
  'MI',
  'FT',
  'BI Data Analyst',
  '100000',
  'USD',
  '100000',
  'US',
  '100',
  'US',
  'M'),
 (77,
  '2021',
  'MI',
  'PT',
  '3D Computer Vision Researcher',
  '400000',
  'INR',
  '5409',
  'IN',
  '50',
  'IN',
  'M'),
 (78,
  '2021',
  'MI',
  'CT',
  'ML Engineer',
  '270000',
  'USD',
  '270000',
  'US',
  '100',
  'US',
  'L'),
 (79,
  '2021',
  'EN',
  'FT',
  'Data Analyst',
  '80000',
  'USD',
  '80000',
  'US',
  '100',
  'US',
  'M'),
 (80,
  '2021',
  'SE',
  'FT',
  'Data Analytics Engineer',
  '67000',
  'EUR',
  '79197',
  'DE',
  '100',
  'DE',
  'L'),
 (81,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '140000',
  'USD',
  '140000',
  'US',
  '100',
  'US',
  'L'),
 (82,
  '2021',
  'MI',
  'FT',
  'Applied Data Scientist',
  '68000',
  'CAD',
  '54238',
  'GB',
  '50',
  'CA',
  'L'),
 (83,
  '2021',
  'MI',
  'FT',
  'Machine Learning Engineer',
  '40000',
  'EUR',
  '47282',
  'ES',
  '100',
  'ES',
  'S'),
 (84,
  '2021',
  'EX',
  'FT',
  'Director of Data Science',
  '130000',
  'EUR',
  '153667',
  'IT',
  '100',
  'PL',
  'L'),
 (85,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '110000',
  'PLN',
  '28476',
  'PL',
  '100',
  'PL',
  'L'),
 (86,
  '2021',
  'EN',
  'FT',
  'Data Analyst',
  '50000',
  'EUR',
  '59102',
  'FR',
  '50',
  'FR',
  'M'),
 (87,
  '2021',
  'MI',
  'FT',
  'Data Analytics Engineer',
  '110000',
  'USD',
  '110000',
  'US',
  '100',
  'US',
  'L'),
 (88,
  '2021',
  'SE',
  'FT',
  'Lead Data Analyst',
  '170000',
  'USD',
  '170000',
  'US',
  '100',
  'US',
  'L'),
 (89,
  '2021',
  'SE',
  'FT',
  'Data Analyst',
  '80000',
  'USD',
  '80000',
  'BG',
  '100',
  'US',
  'S'),
 (90,
  '2021',
  'SE',
  'FT',
  'Marketing Data Analyst',
  '75000',
  'EUR',
  '88654',
  'GR',
  '100',
  'DK',
  'L'),
 (91,
  '2021',
  'EN',
  'FT',
  'Data Science Consultant',
  '65000',
  'EUR',
  '76833',
  'DE',
  '100',
  'DE',
  'S'),
 (92,
  '2021',
  'MI',
  'FT',
  'Lead Data Analyst',
  '1450000',
  'INR',
  '19609',
  'IN',
  '100',
  'IN',
  'L'),
 (93,
  '2021',
  'SE',
  'FT',
  'Lead Data Engineer',
  '276000',
  'USD',
  '276000',
  'US',
  '0',
  'US',
  'L'),
 (94,
  '2021',
  'EN',
  'FT',
  'Data Scientist',
  '2200000',
  'INR',
  '29751',
  'IN',
  '50',
  'IN',
  'L'),
 (95,
  '2021',
  'MI',
  'FT',
  'Cloud Data Engineer',
  '120000',
  'SGD',
  '89294',
  'SG',
  '50',
  'SG',
  'L'),
 (96,
  '2021',
  'EN',
  'PT',
  'AI Scientist',
  '12000',
  'USD',
  '12000',
  'BR',
  '100',
  'US',
  'S'),
 (97,
  '2021',
  'MI',
  'FT',
  'Financial Data Analyst',
  '450000',
  'USD',
  '450000',
  'US',
  '100',
  'US',
  'L'),
 (98,
  '2021',
  'EN',
  'FT',
  'Computer Vision Software Engineer',
  '70000',
  'USD',
  '70000',
  'US',
  '100',
  'US',
  'M'),
 (99,
  '2021',
  'MI',
  'FT',
  'Computer Vision Software Engineer',
  '81000',
  'EUR',
  '95746',
  'DE',
  '100',
  'US',
  'S'),
 (100,
  '2021',
  'MI',
  'FT',
  'Data Analyst',
  '75000',
  'USD',
  '75000',
  'US',
  '0',
  'US',
  'L'),
 (101,
  '2021',
  'SE',
  'FT',
  'Data Engineer',
  '150000',
  'USD',
  '150000',
  'US',
  '100',
  'US',
  'L'),
 (102,
  '2021',
  'MI',
  'FT',
  'BI Data Analyst',
  '11000000',
  'HUF',
  '36259',
  'HU',
  '50',
  'US',
  'L'),
 (103,
  '2021',
  'MI',
  'FT',
  'Data Analyst',
  '62000',
  'USD',
  '62000',
  'US',
  '0',
  'US',
  'L'),
 (104,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '73000',
  'USD',
  '73000',
  'US',
  '0',
  'US',
  'L'),
 (105,
  '2021',
  'MI',
  'FT',
  'Data Analyst',
  '37456',
  'GBP',
  '51519',
  'GB',
  '50',
  'GB',
  'L'),
 (106,
  '2021',
  'MI',
  'FT',
  'Research Scientist',
  '235000',
  'CAD',
  '187442',
  'CA',
  '100',
  'CA',
  'L'),
 (107,
  '2021',
  'SE',
  'FT',
  'Data Engineer',
  '115000',
  'USD',
  '115000',
  'US',
  '100',
  'US',
  'S'),
 (108,
  '2021',
  'SE',
  'FT',
  'Data Engineer',
  '150000',
  'USD',
  '150000',
  'US',
  '100',
  'US',
  'M'),
 (109,
  '2021',
  'EN',
  'FT',
  'Data Engineer',
  '2250000',
  'INR',
  '30428',
  'IN',
  '100',
  'IN',
  'L'),
 (110,
  '2021',
  'SE',
  'FT',
  'Machine Learning Engineer',
  '80000',
  'EUR',
  '94564',
  'DE',
  '50',
  'DE',
  'L'),
 (111,
  '2021',
  'SE',
  'FT',
  'Director of Data Engineering',
  '82500',
  'GBP',
  '113476',
  'GB',
  '100',
  'GB',
  'M'),
 (112,
  '2021',
  'SE',
  'FT',
  'Lead Data Engineer',
  '75000',
  'GBP',
  '103160',
  'GB',
  '100',
  'GB',
  'S'),
 (113,
  '2021',
  'EN',
  'PT',
  'AI Scientist',
  '12000',
  'USD',
  '12000',
  'PK',
  '100',
  'US',
  'M'),
 (114,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '38400',
  'EUR',
  '45391',
  'NL',
  '100',
  'NL',
  'L'),
 (115,
  '2021',
  'EN',
  'FT',
  'Machine Learning Scientist',
  '225000',
  'USD',
  '225000',
  'US',
  '100',
  'US',
  'L'),
 (116,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '50000',
  'USD',
  '50000',
  'NG',
  '100',
  'NG',
  'L'),
 (117,
  '2021',
  'MI',
  'FT',
  'Data Science Engineer',
  '34000',
  'EUR',
  '40189',
  'GR',
  '100',
  'GR',
  'M'),
 (118,
  '2021',
  'EN',
  'FT',
  'Data Analyst',
  '90000',
  'USD',
  '90000',
  'US',
  '100',
  'US',
  'S'),
 (119,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '200000',
  'USD',
  '200000',
  'US',
  '100',
  'US',
  'L'),
 (120,
  '2021',
  'MI',
  'FT',
  'Big Data Engineer',
  '60000',
  'USD',
  '60000',
  'ES',
  '50',
  'RO',
  'M'),
 (121,
  '2021',
  'SE',
  'FT',
  'Principal Data Engineer',
  '200000',
  'USD',
  '200000',
  'US',
  '100',
  'US',
  'M'),
 (122,
  '2021',
  'EN',
  'FT',
  'Data Analyst',
  '50000',
  'USD',
  '50000',
  'US',
  '100',
  'US',
  'M'),
 (123,
  '2021',
  'EN',
  'FT',
  'Applied Data Scientist',
  '80000',
  'GBP',
  '110037',
  'GB',
  '0',
  'GB',
  'L'),
 (124,
  '2021',
  'EN',
  'PT',
  'Data Analyst',
  '8760',
  'EUR',
  '10354',
  'ES',
  '50',
  'ES',
  'M'),
 (125,
  '2021',
  'MI',
  'FT',
  'Principal Data Scientist',
  '151000',
  'USD',
  '151000',
  'US',
  '100',
  'US',
  'L'),
 (126,
  '2021',
  'SE',
  'FT',
  'Machine Learning Scientist',
  '120000',
  'USD',
  '120000',
  'US',
  '50',
  'US',
  'S'),
 (127,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '700000',
  'INR',
  '9466',
  'IN',
  '0',
  'IN',
  'S'),
 (128,
  '2021',
  'EN',
  'FT',
  'Machine Learning Engineer',
  '20000',
  'USD',
  '20000',
  'IN',
  '100',
  'IN',
  'S'),
 (129,
  '2021',
  'SE',
  'FT',
  'Lead Data Scientist',
  '3000000',
  'INR',
  '40570',
  'IN',
  '50',
  'IN',
  'L'),
 (130,
  '2021',
  'EN',
  'FT',
  'Machine Learning Developer',
  '100000',
  'USD',
  '100000',
  'IQ',
  '50',
  'IQ',
  'S'),
 (131,
  '2021',
  'EN',
  'FT',
  'Data Scientist',
  '42000',
  'EUR',
  '49646',
  'FR',
  '50',
  'FR',
  'M'),
 (132,
  '2021',
  'MI',
  'FT',
  'Applied Machine Learning Scientist',
  '38400',
  'USD',
  '38400',
  'VN',
  '100',
  'US',
  'M'),
 (133,
  '2021',
  'SE',
  'FT',
  'Computer Vision Engineer',
  '24000',
  'USD',
  '24000',
  'BR',
  '100',
  'BR',
  'M'),
 (134,
  '2021',
  'EN',
  'FT',
  'Data Scientist',
  '100000',
  'USD',
  '100000',
  'US',
  '0',
  'US',
  'S'),
 (135,
  '2021',
  'MI',
  'FT',
  'Data Analyst',
  '90000',
  'USD',
  '90000',
  'US',
  '100',
  'US',
  'M'),
 (136,
  '2021',
  'MI',
  'FT',
  'ML Engineer',
  '7000000',
  'JPY',
  '63711',
  'JP',
  '50',
  'JP',
  'S'),
 (137,
  '2021',
  'MI',
  'FT',
  'ML Engineer',
  '8500000',
  'JPY',
  '77364',
  'JP',
  '50',
  'JP',
  'S'),
 (138,
  '2021',
  'SE',
  'FT',
  'Principal Data Scientist',
  '220000',
  'USD',
  '220000',
  'US',
  '0',
  'US',
  'L'),
 (139,
  '2021',
  'EN',
  'FT',
  'Data Scientist',
  '80000',
  'USD',
  '80000',
  'US',
  '100',
  'US',
  'M'),
 (140,
  '2021',
  'MI',
  'FT',
  'Data Analyst',
  '135000',
  'USD',
  '135000',
  'US',
  '100',
  'US',
  'L'),
 (141,
  '2021',
  'SE',
  'FT',
  'Data Science Manager',
  '240000',
  'USD',
  '240000',
  'US',
  '0',
  'US',
  'L'),
 (142,
  '2021',
  'SE',
  'FT',
  'Data Engineering Manager',
  '150000',
  'USD',
  '150000',
  'US',
  '0',
  'US',
  'L'),
 (143,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '82500',
  'USD',
  '82500',
  'US',
  '100',
  'US',
  'S'),
 (144,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '100000',
  'USD',
  '100000',
  'US',
  '100',
  'US',
  'L'),
 (145,
  '2021',
  'SE',
  'FT',
  'Machine Learning Engineer',
  '70000',
  'EUR',
  '82744',
  'BE',
  '50',
  'BE',
  'M'),
 (146,
  '2021',
  'MI',
  'FT',
  'Research Scientist',
  '53000',
  'EUR',
  '62649',
  'FR',
  '50',
  'FR',
  'M'),
 (147,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '90000',
  'USD',
  '90000',
  'US',
  '100',
  'US',
  'L'),
 (148,
  '2021',
  'SE',
  'FT',
  'Data Engineering Manager',
  '153000',
  'USD',
  '153000',
  'US',
  '100',
  'US',
  'L'),
 (149,
  '2021',
  'SE',
  'FT',
  'Cloud Data Engineer',
  '160000',
  'USD',
  '160000',
  'BR',
  '100',
  'US',
  'S'),
 (150,
  '2021',
  'SE',
  'FT',
  'Director of Data Science',
  '168000',
  'USD',
  '168000',
  'JP',
  '0',
  'JP',
  'S'),
 (151,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '150000',
  'USD',
  '150000',
  'US',
  '100',
  'US',
  'M'),
 (152,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '95000',
  'CAD',
  '75774',
  'CA',
  '100',
  'CA',
  'L'),
 (153,
  '2021',
  'EN',
  'FT',
  'Data Scientist',
  '13400',
  'USD',
  '13400',
  'UA',
  '100',
  'UA',
  'L'),
 (154,
  '2021',
  'SE',
  'FT',
  'Data Science Manager',
  '144000',
  'USD',
  '144000',
  'US',
  '100',
  'US',
  'L'),
 (155,
  '2021',
  'SE',
  'FT',
  'Data Science Engineer',
  '159500',
  'CAD',
  '127221',
  'CA',
  '50',
  'CA',
  'L'),
 (156,
  '2021',
  'MI',
  'FT',
  'Data Scientist',
  '160000',
  'SGD',
  '119059',
  'SG',
  '100',
  'IL',
  'M'),
 (157,
  '2021',
  'MI',
  'FT',
  'Applied Machine Learning Scientist',
  '423000',
  'USD',
  '423000',
  'US',
  '50',
  'US',
  'L'),
 (158,
  '2021',
  'SE',
  'FT',
  'Data Analytics Manager',
  '120000',
  'USD',
  '120000',
  'US',
  '100',
  'US',
  'M'),
 (159,
  '2021',
  'EN',
  'FT',
  'Machine Learning Engineer',
  '125000',
  'USD',
  '125000',
  'US',
  '100',
  'US',
  'S'),
 (160,
  '2021',
  'EX',
  'FT',
  'Head of Data',
  '230000',
  'USD',
  '230000',
  'RU',
  '50',
  'RU',
  'L'),
 (161,
  '2021',
  'EX',
  'FT',
  'Head of Data Science',
  '85000',
  'USD',
  '85000',
  'RU',
  '0',
  'RU',
  'M'),
 (162,
  '2021',
  'MI',
  'FT',
  'Data Engineer',
  '24000',
  'EUR',
  '28369',
  'MT',
  '50',
  'MT',
  'L'),
 (163,
  '2021',
  'EN',
  'FT',
  'Data Science Consultant',
  '54000',
  'EUR',
  '63831',
  'DE',
  '50',
  'DE',
  'L'),
 (164,
  '2021',
  'EX',
  'FT',

## Save Data to CSV Files

Since CSV file is much more convenient to process, we still use pandas to convert and to write to CSV files.

In [3]:
import pandas as pd

df = pd.DataFrame(results)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       607 non-null    float64
 1   1       608 non-null    object
 2   2       608 non-null    object
 3   3       608 non-null    object
 4   4       608 non-null    object
 5   5       608 non-null    object
 6   6       608 non-null    object
 7   7       608 non-null    object
 8   8       608 non-null    object
 9   9       608 non-null    object
 10  10      608 non-null    object
 11  11      608 non-null    object
dtypes: float64(1), object(11)
memory usage: 57.1+ KB

In [4]:
df.iloc[0]

0                    NaN
1              work_year
2       experience_level
3        employment_type
4              job_title
5                 salary
6        salary_currency
7          salary_in_usd
8     employee_residence
9           remote_ratio
10      company_location
11          company_size
Name: 0, dtype: object

In [5]:
cols = list(df.iloc[0])
cols

[nan,
 'work_year',
 'experience_level',
 'employment_type',
 'job_title',
 'salary',
 'salary_currency',
 'salary_in_usd',
 'employee_residence',
 'remote_ratio',
 'company_location',
 'company_size']

In [6]:
df.columns = cols
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nan                 607 non-null    float64
 1   work_year           608 non-null    object
 2   experience_level    608 non-null    object
 3   employment_type     608 non-null    object
 4   job_title           608 non-null    object
 5   salary              608 non-null    object
 6   salary_currency     608 non-null    object
 7   salary_in_usd       608 non-null    object
 8   employee_residence  608 non-null    object
 9   remote_ratio        608 non-null    object
 10  company_location    608 non-null    object
 11  company_size        608 non-null    object
dtypes: float64(1), object(11)
memory usage: 57.1+ KB

In [7]:
df.drop(0, inplace = True)
df

,NaN,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
1,0.0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
2,1.0,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
3,2.0,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
4,3.0,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
5,4.0,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
603,602.0,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
604,603.0,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
605,604.0,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
606,605.0,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
607,606.0,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [8]:
cursor.close()
connection.close()